sudo: required
language: python
python: 3.7-dev
before_install:
  - echo $SERVICE_ACCOUNT > service-account.json
install:
  - pip install -r requirements.txt
deploy:
  provider: gae
  keyfile: service-account.json
  project: kawalc1
  on: master
